# Generated by Django 4.0.3 on 2022-04-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text="13 Character &lt;a href='https://www.isbn-international.org/content/what-isbn'&gt;ISBN number&lt;/a&gt;", max_length=15)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Enter brief description of the book', max_length=500)),
                ('available_copies', models.IntegerField()),
                ('genre', models.ManyToManyField(to='books.genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language')),
            ],
        ),
    ]
