# Generated by Django 4.0.3 on 2022-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the book', max_length=100)),
                ('author', models.TextField(blank=True, help_text='Author of this book', max_length=200, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('recommended_by', models.EmailField(max_length=254)),
                ('recommended_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
