# Generated by Django 4.0.3 on 2022-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_recommendedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbook',
            name='author',
            field=models.CharField(blank=True, help_text='Author of this book', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='isbn',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='title',
            field=models.CharField(help_text='Title of the book', max_length=100),
        ),
    ]
