# Generated by Django 4.0.3 on 2022-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_recommendedbook_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
