# Generated by Django 4.0.3 on 2022-04-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_small_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
