# Generated by Django 4.0.3 on 2022-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_issueddetail_book_alter_issueddetail_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
