# Generated by Django 4.0.3 on 2022-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embeddable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
