# Generated by Django 4.0.3 on 2022-05-02 14:17

import books.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=books.models.ListField(blank=True, null=True, token=','),
        ),
    ]
