# Generated by Django 4.0.3 on 2022-05-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
