# Generated by Django 4.0.3 on 2022-05-02 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_bookreview_delete_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssuedDetail',
            new_name='BorrowedBooks',
        ),
    ]
