# Generated by Django 4.0.3 on 2022-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_rename_issueddetail_borrowedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], help_text='Rate this book on the scale of 1 - 5', null=True),
        ),
    ]
