# Generated by Django 4.0.3 on 2022-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_bookreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character ISBN number (https://www.isbn-international.org/content/what-isbn)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter brief description of the book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate this book on the scale of 1 - 5', null=True),
        ),
    ]
